# Generated by Django 4.1 on 2022-09-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='autos'),
        ),
        migrations.AlterField(
            model_name='camioneta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='camionetas'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='motos'),
        ),
    ]
