# Generated by Django 4.1 on 2022-09-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_remove_auto_imagen_autoimagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoimagen',
            old_name='vehiculo',
            new_name='auto',
        ),
    ]
