# Generated by Django 4.1 on 2022-09-17 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_rename_vehiculo_autoimagen_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoimagen',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.auto'),
        ),
    ]
