# Generated by Django 4.1 on 2022-09-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_alter_autoimagen_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoimagen',
            name='auto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.auto'),
        ),
    ]
