# Generated by Django 4.1 on 2022-09-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0006_alter_autoimagen_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
