# Generated by Django 4.1 on 2022-09-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0007_alter_auto_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='motos')),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.auto')),
            ],
        ),
        migrations.CreateModel(
            name='CamionetaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='camionetas')),
                ('auto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.camioneta')),
            ],
        ),
    ]
