# Generated by Django 4.1 on 2022-09-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0008_motoimagen_camionetaimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camioneta',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='moto',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='camioneta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='moto',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
