# Generated by Django 4.1 on 2022-09-18 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0009_remove_camioneta_imagen_remove_moto_imagen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camionetaimagen',
            old_name='auto',
            new_name='camioneta',
        ),
        migrations.RenameField(
            model_name='motoimagen',
            old_name='auto',
            new_name='moto',
        ),
    ]
