# Generated by Django 4.1 on 2022-09-24 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0010_rename_auto_camionetaimagen_camioneta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoimagen',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='camionetaimagen',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='motoimagen',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='motoimagen',
            name='moto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppBlog.moto'),
        ),
    ]
