# Generated by Django 4.1 on 2022-09-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0012_rename_nombre_autoimagen_articulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autoimagen',
            old_name='model',
            new_name='auto',
        ),
        migrations.RenameField(
            model_name='camionetaimagen',
            old_name='model',
            new_name='Camioneta',
        ),
        migrations.RenameField(
            model_name='motoimagen',
            old_name='model',
            new_name='moto',
        ),
    ]
