# Generated by Django 4.1 on 2022-09-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0013_rename_model_autoimagen_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='autos'),
        ),
    ]
