# Generated by Django 4.1 on 2022-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0014_auto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camionetaimagen',
            name='Camioneta',
        ),
        migrations.RemoveField(
            model_name='motoimagen',
            name='moto',
        ),
        migrations.AddField(
            model_name='camioneta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='autos'),
        ),
        migrations.AddField(
            model_name='moto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='autos'),
        ),
        migrations.DeleteModel(
            name='AutoImagen',
        ),
        migrations.DeleteModel(
            name='CamionetaImagen',
        ),
        migrations.DeleteModel(
            name='MotoImagen',
        ),
    ]
