# Generated by Django 4.1 on 2022-10-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0016_alter_camioneta_imagen_alter_moto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cuerpo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='camioneta',
            name='cuerpo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='moto',
            name='cuerpo',
            field=models.CharField(max_length=1000),
        ),
    ]
