# Generated by Django 4.1 on 2022-10-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0018_alter_auto_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='cuerpo',
            field=models.CharField(max_length=1000),
        ),
    ]
